# Resources/config/services.yml
services:

    logger:
        alias: "monolog.logger"
        public: true

    webeweb.bootstrap.eventlistener.kernel:
        class:     WBW\Bundle\BootstrapBundle\EventListener\KernelEventListener
        arguments: ["@security.token_storage", "@webeweb.bootstrap.manager.theme"]
        public:    true
        tags:
            - { name: "kernel.event_listener", event: "kernel.exception", method: "onKernelException" }
            - { name: "kernel.event_listener", event: "kernel.request",   method: "onKernelRequest" }

    webeweb.bootstrap.eventlistener.notification:
        class:     WBW\Bundle\BootstrapBundle\EventListener\NotificationEventListener
        arguments: ["@webeweb.bootstrap.eventlistener.kernel"]
        tags:
            - { name: "kernel.event_listener", event: "webeweb.bootstrap.event.notification.danger",  method: "onNotify" }
            - { name: "kernel.event_listener", event: "webeweb.bootstrap.event.notification.info",    method: "onNotify" }
            - { name: "kernel.event_listener", event: "webeweb.bootstrap.event.notification.success", method: "onNotify" }
            - { name: "kernel.event_listener", event: "webeweb.bootstrap.event.notification.warning", method: "onNotify" }

    webeweb.bootstrap.manager.theme:
        class:     WBW\Bundle\BootstrapBundle\Manager\ThemeManager
        arguments: ["@twig"]
        calls:
            - ["setApplicationProvider",           ["@?webeweb.bootstrap.provider.application"]]
            - ["setBreadcrumbsProvider",           ["@?webeweb.bootstrap.provider.breadcrumbs"]]
            - ["setDropDownHookProvider",          ["@?webeweb.bootstrap.provider.dropdownhook"]]
            - ["setDropDownNotificationsProvider", ["@?webeweb.bootstrap.provider.dropdownnotifications"]]
            - ["setDropDownTasksProvider",         ["@?webeweb.bootstrap.provider.dropdowntasks"]]
            - ["setFooterProvider",                ["@?webeweb.bootstrap.provider.footer"]]
            - ["setNavigationProvider",            ["@?webeweb.bootstrap.provider.navigation"]]
            - ["setSearchProvider",                ["@?webeweb.bootstrap.provider.search"]]
            - ["setUserInfoProvider",              ["@?webeweb.bootstrap.provider.userinfo"]]

    webeweb.bootstrap.manager.asset.css:
        class:     WBW\Bundle\BootstrapBundle\Manager\Asset\CSSAssetManager
        arguments: ["%kernel.root_dir%/../web"]

    webeweb.bootstrap.manager.asset.js:
        class:     WBW\Bundle\BootstrapBundle\Manager\Asset\JSAssetManager
        arguments: ["%kernel.root_dir%/../web"]

    webeweb.bootstrap.twig.extension.css.button:
        class: WBW\Bundle\BootstrapBundle\Twig\Extension\CSS\ButtonTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.css.code:
        class: WBW\Bundle\BootstrapBundle\Twig\Extension\CSS\CodeTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.css.grid:
        class: WBW\Bundle\BootstrapBundle\Twig\Extension\CSS\GridTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.css.image:
        class: WBW\Bundle\BootstrapBundle\Twig\Extension\CSS\ImageTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.css.typography:
        class: WBW\Bundle\BootstrapBundle\Twig\Extension\CSS\TypographyTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.component.alert:
        class: WBW\Bundle\BootstrapBundle\Twig\Extension\Component\AlertTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.component.badge:
        class: WBW\Bundle\BootstrapBundle\Twig\Extension\Component\BadgeTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.component.breadcrumb:
        class:     WBW\Bundle\BootstrapBundle\Twig\Extension\Component\BreadcrumbTwigExtension
        arguments: ["@translator"]
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.component.buttongroup:
        class: WBW\Bundle\BootstrapBundle\Twig\Extension\Component\ButtonGroupTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.component.dropdown:
        class: WBW\Bundle\BootstrapBundle\Twig\Extension\Component\DropdownTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.component.glyphicon:
        class: WBW\Bundle\BootstrapBundle\Twig\Extension\Component\GlyphiconTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.component.label:
        class: WBW\Bundle\BootstrapBundle\Twig\Extension\Component\LabelTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.component.nav:
        class: WBW\Bundle\BootstrapBundle\Twig\Extension\Component\NavTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.component.progressbar:
        class: WBW\Bundle\BootstrapBundle\Twig\Extension\Component\ProgressBarTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.plugin.fontawesome:
        class: WBW\Bundle\BootstrapBundle\Twig\Extension\Plugin\FontAwesomeTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.plugin.jqueryinputmask:
        class:     WBW\Bundle\BootstrapBundle\Twig\Extension\Plugin\JQueryInputMaskTwigExtension
        arguments: ["@webeweb.bootstrap.twig.extension.renderer"]
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.plugin.materialdesigniconicfont:
        class: WBW\Bundle\BootstrapBundle\Twig\Extension\Plugin\MaterialDesignIconicFontTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.plugin.meteocons:
        class: WBW\Bundle\BootstrapBundle\Twig\Extension\Plugin\MeteoconsTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.renderer:
        class: WBW\Bundle\BootstrapBundle\Twig\Extension\BootstrapRendererTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.utility.formbutton:
        class:     WBW\Bundle\BootstrapBundle\Twig\Extension\Utility\FormButtonTwigExtension
        arguments: ["@translator", "@webeweb.bootstrap.twig.extension.css.button"]
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.utility.rolelabel:
        class:     WBW\Bundle\BootstrapBundle\Twig\Extension\Utility\RoleLabelTwigExtension
        arguments: ["@translator", "@webeweb.bootstrap.twig.extension.component.label"]
        tags:
            - { name: "twig.extension" }

    webeweb.bootstrap.twig.extension.utility.tablebutton:
        class:     WBW\Bundle\BootstrapBundle\Twig\Extension\Utility\TableButtonTwigExtension
        arguments: ["@translator", "@webeweb.bootstrap.twig.extension.css.button"]
        tags:
            - { name: "twig.extension" }
