# .travis.yml
language: "php"

php:
    - "5.6"
    - "7.0"
    - "7.1"
    - "7.2"
    - "7.3"
    - "7.4"
    - "nightly"

jobs:
    include:
        -   php: "5.6"
            env: "SYMFONY_VERSION=2.7.*"
        -   php: "5.6"
            env: "SYMFONY_VERSION=2.8.*"
        -   php: "5.6"
            env: "SYMFONY_VERSION=3.0.*"
        -   php: "5.6"
            env: "SYMFONY_VERSION=3.1.*"
        -   php: "5.6"
            env: "SYMFONY_VERSION=3.2.*"
        -   php: "5.6"
            env: "SYMFONY_VERSION=3.3.*"
        -   php: "5.6"
            env: "SYMFONY_VERSION=3.4.*"
        -   php: "7.1"
            env: "SYMFONY_VERSION=4.0.*"
        -   php: "7.1"
            env: "SYMFONY_VERSION=4.1.*"
        -   php: "7.1"
            env: "SYMFONY_VERSION=4.2.*"
        -   php: "7.1"
            env: "SYMFONY_VERSION=4.3.*"
        -   php: "7.1"
            env: "SYMFONY_VERSION=4.4.*"
    allow_failures:
        -   php: "nightly"

os: linux

before_install:
    - sudo /bin/dd if=/dev/zero of=/var/swap bs=1M count=1024
    - sudo /sbin/mkswap /var/swap
    - sudo /sbin/swapon /var/swap
    #- echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - if [ "" != "$SYMFONY_VERSION" ]; then COMPOSER_MEMORY_LIMIT=-1 composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; else COMPOSER_MEMORY_LIMIT=-1 composer require "symfony/symfony:3.4.*"; fi;

install:
    - COMPOSER_MEMORY_LIMIT=-1 composer update
    - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar -O coveralls.phar
    - chmod +x coveralls.phar
    - php coveralls.phar --version

before_script:
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - php coveralls.phar -v

notifications:
    email:
        on_failure: "always"
        on_success: "always"
