# .github/workflows/analysis.yml
name: "analysis"

on: [ push ]

jobs:

    build:
        name:    "PHPStan"
        runs-on: ubuntu-18.04

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v2

            -   name: "Build environment"
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "7.1"
                    coverage:    "xdebug"

            -   name: "Dependencies"
                run:  |
                      php --version
                      composer --version
                      COMPOSER_MEMORY_LIMIT=-1 composer update

            -   name: "Application"
                run:  |
                      mkdir -p build/logs
                      wget -c -nc --retry-connrefused --tries=0 https://github.com/phpstan/phpstan/releases/download/0.12.99/phpstan.phar -O phpstan.phar
                      chmod +x phpstan.phar
                      php phpstan.phar --version
                      echo -e "parameters:\n    level: 0\n    excludePaths:\n        -   \"Resources/*\"\n        -   \"Tests/*\"\n        -   \"vendor/*\"" > phpstan.neon

            -   name: "Analyses"
                run:  php phpstan.phar analyse . --error-format=github --configuration phpstan.neon
