# .github/workflows/build.yml
name: "Unit tests"

on: [ push ]

jobs:

    build:
        name:    "PHP ${{ matrix.php-version }}${{ matrix.symfony-label }}"
        runs-on: ubuntu-22.04

        strategy:
            matrix:
                include:
                    -   php-version: "7.1"
                    -   php-version: "7.2"
                    -   php-version: "7.3"
                    -   php-version: "7.4"
                    -   php-version: "8.0"
                    -   php-version: "8.1"
                    -   php-version: "8.2"
                    -   php-version:     "7.1"
                        symfony-version: "4.4.*"
                        symfony-label:   ": Symfony 4.4.*"
                    -   php-version:     "7.2"
                        symfony-version: "5.0.*"
                        symfony-label:   ": Symfony 5.0.*"
                    -   php-version:     "7.2"
                        symfony-version: "5.1.*"
                        symfony-label:   ": Symfony 5.1.*"
                    -   php-version:     "7.2"
                        symfony-version: "5.2.*"
                        symfony-label:   ": Symfony 5.2.*"
                    -   php-version:     "7.2"
                        symfony-version: "5.3.*"
                        symfony-label:   ": Symfony 5.3.*"
                    -   php-version:     "7.2"
                        symfony-version: "5.4.*"
                        symfony-label:   ": Symfony 5.4.*"

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v3

            -   name: "Build environment"
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php-version }}"
                    coverage:    "xdebug"

            -   name: "Dependencies"
                run:  |
                      php --version
                      composer --version
                      if [ "" != "${{ matrix.symfony-version }}" ]; then SYMFONY_VERSION=${{ matrix.symfony-version }}; else SYMFONY_VERSION="4.4.*"; fi;
                      COMPOSER_MEMORY_LIMIT=-1 composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update
                      COMPOSER_MEMORY_LIMIT=-1 composer update

            -   name: "Application"
                run:  |
                      mkdir -p build/logs
                      wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.5.3/php-coveralls.phar -O coveralls.phar
                      chmod +x coveralls.phar
                      php coveralls.phar --version

            -   name: "Tests"
                run:  vendor/bin/phpunit --coverage-clover build/logs/clover.xml

            -   name: "Coverage"
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    COVERALLS_FLAG_NAME:  php-${{ matrix.php-version }}
                    COVERALLS_PARALLEL:   true
                run:  php coveralls.phar -v

    coverage:
        name:    "Coverage"
        runs-on: ubuntu-22.04
        needs:   "build"
        if:      always()

        steps:
            -   name: "Coverage"
                uses: coverallsapp/github-action@1.1.3
                with:
                    github-token:      ${{ secrets.github_token }}
                    parallel-finished: true
